### ISSUE TITLE
Error: TypeError: Path must be a string. Received null on latest version for sample code provided

### ISSUE THREAD

**Issue by Sumit-Soman** [NimaSoroush/Mockeer#5]
Error: TypeError: Path must be a string. Received null on latest version for sample code provided
code used
const mockeer = require('mockeer');
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await mockeer(browser);
  await page.goto('url');
  await page.close();
  await browser.close();
})();

(node:43532) UnhandledPromiseRejectionWarning: TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at getFixtureFolder (C:\Users\S730737\Documents\EK.com\Projects\carbon-visual-regression\node_modules\mockeer\src\helpers\file-helper.js:5:65)
    at sanitiseConfiguration (C:\Users\S730737\Documents\EK.com\Projects\carbon-visual-regression\node_modules\mockeer\src\sanitiser.js:30:33)
    at recorder (C:\Users\S730737\Documents\EK.com\Projects\carbon-visual-regression\node_modules\mockeer\src\index.js:14:18)
    at C:\Users\S730737\Documents\EK.com\Projects\carbon-visual-regression\lib\mockeer.js:7:9

library
"mockeer": "0.0.3",
"puppeteer": "^1.13.0",

Kindly suggest if something I am missing.

I am tring to load a url and mock the images for the same using mockeer

**Comment by NimaSoroush** [comment]
Hi @Sumit-Soman :

Thanks for raising this. I had a quick look and the error seems to be happening because you are running the test outside Jest environment and you are not providing `fixturesDir` value either. I will put a fix for this to not throw exceptions and default it to a meaningful value but meanwhile you can change your script to be like 

```
const puppeteer = require('puppeteer');
const mockeer = require('./src/index');

(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  await mockeer(browser, { fixturesDir: '.' });
  await page.goto('http://example.com/');
  await page.close();
  await browser.close();
})();
```

**Comment by Sumit-Soman** [comment]
Thanks @NimaSoroush for the quick reply. Appreciate it

**Comment by NimaSoroush** [comment]
mockeer@0.0.4 published which fixes the issue.
